REM http://www.medicareaustralia.gov.au/provider/vendors/healthcare-identifiers-developers/licensed-material/current-versions.jsp
@echo OFF
cls
@echo ============================================================================
@echo --- DELETE FILES NOT REQUIRED                                            ---
@echo ============================================================================

DEL .\fw\*.cs \Q

@echo ============================================================================
@echo --- Building WSDL proxies                                                ---
@echo ============================================================================
REM SET WSDLTOOL="c:\Program Files\Microsoft SDKs\Windows\v6.0A\Bin\SvcUtil.exe" /noLogo
SET WSDLTOOL="C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\SvcUtil.exe" /noLogo
@echo ON

@echo Consumer - 11
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100731\HI_ConsumerCreateProvisionalIHI*.wsdl   					schema\mca\consumer\messages\20100731\CreateProvisionalIHIMessages.xsd   					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R3-ConsumerCreateProvisionalIHI.cs   					  /config:mca.config /namespace:*,nehta.mcaR3.ConsumerCreateProvisionalIHI     					/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100731\HI_ConsumerMergeProvisionalIHI*.wsdl    					schema\mca\consumer\messages\20100731\MergeProvisionalIHIMessages.xsd    					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R3-ConsumerMergeProvisionalIHI.cs    					  /config:mca.config /namespace:*,nehta.mcaR3.ConsumerMergeProvisionalIHI      					/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100731\HI_ConsumerSearchIHI-*.wsdl  wsdl\consumer\20100731\HI_ConsumerSearchIHIInterface*.wsdl schema\mca\consumer\messages\20100731\SearchIHIMessages.xsd 	schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R3-ConsumerSearchIHI.cs 								  /config:mca.config /namespace:*,nehta.mcaR3.ConsumerSearchIHI  								/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100731\HI_ConsumerSearchIHIBatchAsync*.wsdl    					schema\mca\consumer\messages\20100731\SearchIHI*Messages.xsd             					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R3-ConsumerSearchIHIBatchAsync.cs    					  /config:mca.config /namespace:*,nehta.mcaR3.ConsumerSearchIHIBatchAsync      					/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100731\HI_ConsumerSearchIHIBatchSync*.wsdl    					schema\mca\consumer\messages\20100731\SearchIHI*Messages.xsd             					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R3-ConsumerSearchIHIBatchSync.cs     				  	  /config:mca.config /namespace:*,nehta.mcaR3.ConsumerSearchIHIBatchSync       					/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100731\HI_ConsumerUpdateProvisionalIHI*.wsdl   					schema\mca\consumer\messages\20100731\UpdateProvisionalIHIMessages.xsd   					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R3-ConsumerUpdateProvisionalIHI.cs   					  /config:mca.config /namespace:*,nehta.mcaR3.ConsumerUpdateProvisionalIHI     					/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100930\HI_ConsumerNotifyDuplicateIHI*.wsdl     					schema\mca\consumer\messages\20100930\NotifyDuplicateIHIMessages.xsd     					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100930\*.xsd /out:.\fw\R32-ConsumerNotifyDuplicateIHI.cs     					  /config:mca.config /namespace:*,nehta.mcaR32.ConsumerNotifyDuplicateIHI       				/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100930\HI_ConsumerNotifyReplicaIHI*.wsdl       					schema\mca\consumer\messages\20100930\NotifyReplicaIHIMessages.xsd       					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100930\*.xsd /out:.\fw\R32-ConsumerNotifyReplicaIHI.cs       					  /config:mca.config /namespace:*,nehta.mcaR32.ConsumerNotifyReplicaIHI         				/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100930\HI_ConsumerUpdateIHI*.wsdl                                 schema\mca\consumer\messages\20100930\UpdateIHIMessages.xsd              					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100930\*.xsd schema\mca\consumer\core\20100731\*.xsd    /out:.\fw\R32-ConsumerUpdateIHI.cs    /config:mca.config /namespace:*,nehta.mcaR32.ConsumerUpdateIHI     				/tcv:Version35

%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100821\HI_ConsumerCreateUnverifiedIHI*.wsdl    					schema\mca\consumer\messages\20100731\CreateUnverifiedIHIMessages.xsd    					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R302-ConsumerCreateUnverifiedIHI.cs    				  /config:mca.config /namespace:*,nehta.mcaR302.ConsumerCreateUnverifiedIHI      				/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20100821\HI_ConsumerResolveProvisionalIHI*.wsdl  					schema\mca\consumer\messages\20100731\ResolveProvisionalIHIMessages.xsd  					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R302-ConsumerResolveProvisionalIHI.cs  				  /config:mca.config /namespace:*,nehta.mcaR302.ConsumerResolveProvisionalIHI    				/tcv:Version35

%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\consumer\20111201\HI_ConsumerCreateVerifiedIHI*.wsdl   schema\mca\consumer\messages\20111201\CreateVerifiedIHI.xsd   	schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd /out:.\fw\R40-CreateVerifiedIHI.cs     /config:mca.config /namespace:*,nehta.mcaR40.CreateVerifiedIHI     					/tcv:Version35

@echo provider - 10
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20100930\HI_ProviderManageProviderAdministrativeIndividual*.wsdl    schema\mca\provider\messages\20100930\ManageProviderAdministrativeIndividualMessages.xsd    schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd /out:.\fw\R32-ProviderManageProviderAdministrativeIndividual.cs    /config:mca.config /namespace:*,nehta.mcaR32.ProviderManageProviderAdministrativeIndividual      /tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20100930\HI_ProviderManageProviderDirectoryEntry*.wsdl              schema\mca\provider\messages\20100930\ManageProviderDirectoryEntryMessages.xsd              schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd /out:.\fw\R32-ProviderManageProviderDirectoryEntry.cs              /config:mca.config /namespace:*,nehta.mcaR32.ProviderManageProviderDirectoryEntry                /tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20100930\HI_ProviderManageProviderOrganisation*.wsdl                schema\mca\provider\messages\20100930\ManageProviderOrganisationMessages.xsd                schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd /out:.\fw\R32-ProviderManageProviderOrganisation.cs                /config:mca.config /namespace:*,nehta.mcaR32.ProviderManageProviderOrganisation                  /tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20100930\HI_ProviderReadProviderAdministrativeIndividual*.wsdl      schema\mca\provider\messages\20100930\ReadProviderAdministrativeIndividualMessages.xsd      schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd /out:.\fw\R32-ProviderReadProviderAdministrativeIndividual.cs      /config:mca.config /namespace:*,nehta.mcaR32.ProviderReadProviderAdministrativeIndividual        /tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20100930\HI_ProviderReadProviderOrganisation*.wsdl                  schema\mca\provider\messages\20100930\ReadProviderOrganisationMessages.xsd                  schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd /out:.\fw\R32-ProviderReadProviderOrganisation.cs                  /config:mca.config /namespace:*,nehta.mcaR32.ProviderReadProviderOrganisation                    /tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20100930\HI_ProviderReadReferenceData*.wsdl                         schema\mca\provider\messages\20100930\ReadReferenceDataMessages.xsd                         schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd /out:.\fw\R32-ProviderReadReferenceData.cs                         /config:mca.config /namespace:*,nehta.mcaR32.ProviderReadReferenceData                           /tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20100930\HI_ProviderSearchHIProviderDirectoryForIndividual*.wsdl    schema\mca\provider\messages\20100930\SearchHIProviderDirectoryForIndividualMessages.xsd    schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd /out:.\fw\R32-ProviderSearchHIProviderDirectoryForIndividual.cs    /config:mca.config /namespace:*,nehta.mcaR32.ProviderSearchHIProviderDirectoryForIndividual      /tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20100930\HI_ProviderSearchHIProviderDirectoryForOrganisation*.wsdl  schema\mca\provider\messages\20100930\SearchHIProviderDirectoryForOrganisationMessages.xsd  schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd /out:.\fw\R32-ProviderSearchHIProviderDirectoryForOrganisation.cs  /config:mca.config /namespace:*,nehta.mcaR32.ProviderSearchHIProviderDirectoryForOrganisation    /tcv:Version35

%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20130401\HI_ProviderSearchForProviderIndividual*.wsdl     schema\mca\provider\messages\20130401\SearchForProviderIndividualMessages.xsd     schema\w3c\xmldsig-core-schema.xsd   schema\mca\common\20100731\*.xsd   schema\mca\provider\core\20130401\*.xsd  schema\mca\provider\core\20100930\*.xsd /out:.\fw\R50-ProviderSearchForProviderIndividual.cs       /config:mca.config /namespace:*,nehta.mcaR50.ProviderSearchForProviderIndividual     					/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20130401\HI_ProviderSearchForProviderOrganisation*.wsdl   schema\mca\provider\messages\20130401\SearchForProviderOrganisationMessages.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\common\20100731\*.xsd   schema\mca\provider\core\20130401\*.xsd  schema\mca\provider\core\20100930\*.xsd  /out:.\fw\R50-ProviderSearchForProviderOrganisation.cs     /config:mca.config /namespace:*,nehta.mcaR50.ProviderSearchForProviderOrganisation     					/tcv:Version35

%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20130622\HI_ProviderBatchAsyncSearchForProviderIndividual*.wsdl      schema\mca\common\20100731\*.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\provider\core\20130601\ProviderType.xsd         schema\mca\provider\core\20130601\ProviderCoreElements.xsd   schema\mca\provider\core\20130401\*.xsd  schema\mca\provider\core\20100930\*.xsd  schema\mca\provider\messages\20130401\SearchForProviderIndividualMessages.xsd     schema\mca\provider\messages\20130601\RetrieveSearchForProviderIndividualResultsMessages.xsd     schema\mca\provider\messages\20130601\SubmitSearchForProviderIndividualMessages.xsd      /out:.\fw\R51-ProviderBatchAsyncSearchForProviderIndividual.cs      /config:mca.config /namespace:*,nehta.mcaR51.ProviderBatchAsyncSearchForProviderIndividual     	/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20130622\HI_ProviderBatchAsyncSearchForProviderOrganisation*.wsdl    schema\mca\common\20100731\*.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\provider\core\20130601\OrganisationDetails.xsd  schema\mca\provider\core\20130601\ProviderCoreElements.xsd   schema\mca\provider\core\20130401\*.xsd  schema\mca\provider\core\20100930\*.xsd  schema\mca\provider\messages\20130401\SearchForProviderOrganisationMessages.xsd   schema\mca\provider\messages\20130601\RetrieveSearchForProviderOrganisationResultsMessages.xsd   schema\mca\provider\messages\20130601\SubmitSearchForProviderOrganisationMessages.xsd    /out:.\fw\R51-ProviderBatchAsyncSearchForProviderOrganisation.cs    /config:mca.config /namespace:*,nehta.mcaR51.ProviderBatchAsyncSearchForProviderOrganisation     	/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20130622\HI_ProviderManageTdsProviderIndividual*.wsdl              schema\mca\common\20100731\*.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\provider\messages\20100930\ManageTdsProviderIndividualMessages.xsd  schema\mca\provider\core\20100930\*.xsd  schema\mca\provider\core\20130622\*.xsd    /out:.\fw\R51-ProviderManageTdsProviderIndividual.cs              /config:mca.config /namespace:*,nehta.mcaR51.ProviderManageTdsProviderIndividual     				/tcv:Version35
%WSDLTOOL%  /useSerializerForFaults /serializer:XmlSerializer wsdl\provider\20130622\HI_ProviderSearchTdsProviderIndividual*.wsdl              schema\mca\common\20100731\*.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\provider\messages\20100930\SearchTdsProviderIndividualMessages.xsd  schema\mca\provider\core\20100930\*.xsd  schema\mca\provider\core\20130622\*.xsd    /out:.\fw\R51-ProviderSearchTdsProviderIndividual.cs              /config:mca.config /namespace:*,nehta.mcaR51.ProviderSearchTdsProviderIndividual     				/tcv:Version35

DEL *.config
PAUSE
