REM http://www.medicareaustralia.gov.au/provider/vendors/healthcare-identifiers-developers/licensed-material/current-versions.jsp
@echo OFF
cls
@echo ============================================================================
@echo --- DELETE FILES NOT REQUIRED                                            ---
@echo ============================================================================

DEL .\net\*.cs \Q

@echo ============================================================================
@echo --- Building WSDL proxies                                                ---
@echo ============================================================================
REM SET WSDLTOOL="c:\Program Files\Microsoft SDKs\Windows\v6.0A\Bin\SvcUtil.exe" /noLogo
SET WSDLTOOL="C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\SvcUtil.exe" /noLogo
@echo ON

@echo Consumer - 11
dotnet-svcutil wsdl\consumer\20100731\HI_ConsumerCreateProvisionalIHI*.wsdl   					schema\mca\consumer\messages\20100731\CreateProvisionalIHIMessages.xsd   					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R3-ConsumerCreateProvisionalIHI.cs   					  --sync --serializer XmlSerializer --namespace *,nehta.mcaR3.ConsumerCreateProvisionalIHI     					
dotnet-svcutil wsdl\consumer\20100731\HI_ConsumerMergeProvisionalIHI*.wsdl    					schema\mca\consumer\messages\20100731\MergeProvisionalIHIMessages.xsd    					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R3-ConsumerMergeProvisionalIHI.cs    					  --sync --serializer XmlSerializer --namespace *,nehta.mcaR3.ConsumerMergeProvisionalIHI      					
dotnet-svcutil wsdl\consumer\20100731\HI_ConsumerSearchIHI-*.wsdl  wsdl\consumer\20100731\HI_ConsumerSearchIHIInterface*.wsdl schema\mca\consumer\messages\20100731\SearchIHIMessages.xsd 	schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R3-ConsumerSearchIHI.cs 								      --sync --serializer XmlSerializer --namespace *,nehta.mcaR3.ConsumerSearchIHI  								
dotnet-svcutil wsdl\consumer\20100731\HI_ConsumerSearchIHIBatchAsync*.wsdl    					schema\mca\consumer\messages\20100731\SearchIHI*Messages.xsd             					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R3-ConsumerSearchIHIBatchAsync.cs    					  --sync --serializer XmlSerializer --namespace *,nehta.mcaR3.ConsumerSearchIHIBatchAsync      					
dotnet-svcutil wsdl\consumer\20100731\HI_ConsumerSearchIHIBatchSync*.wsdl    					schema\mca\consumer\messages\20100731\SearchIHI*Messages.xsd             					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R3-ConsumerSearchIHIBatchSync.cs     				  	  --sync --serializer XmlSerializer --namespace *,nehta.mcaR3.ConsumerSearchIHIBatchSync       					
dotnet-svcutil wsdl\consumer\20100731\HI_ConsumerUpdateProvisionalIHI*.wsdl   					schema\mca\consumer\messages\20100731\UpdateProvisionalIHIMessages.xsd   					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R3-ConsumerUpdateProvisionalIHI.cs   					  --sync --serializer XmlSerializer --namespace *,nehta.mcaR3.ConsumerUpdateProvisionalIHI     					
dotnet-svcutil wsdl\consumer\20100930\HI_ConsumerNotifyDuplicateIHI*.wsdl     					schema\mca\consumer\messages\20100930\NotifyDuplicateIHIMessages.xsd     					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100930\*.xsd --outputDir .\net --outputFile R32-ConsumerNotifyDuplicateIHI.cs     					  --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ConsumerNotifyDuplicateIHI       				
dotnet-svcutil wsdl\consumer\20100930\HI_ConsumerNotifyReplicaIHI*.wsdl       					schema\mca\consumer\messages\20100930\NotifyReplicaIHIMessages.xsd       					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100930\*.xsd --outputDir .\net --outputFile R32-ConsumerNotifyReplicaIHI.cs       					  --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ConsumerNotifyReplicaIHI         				
dotnet-svcutil wsdl\consumer\20100930\HI_ConsumerUpdateIHI*.wsdl                                 schema\mca\consumer\messages\20100930\UpdateIHIMessages.xsd              					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100930\*.xsd schema\mca\consumer\core\20100731\*.xsd    --outputDir .\net --outputFile R32-ConsumerUpdateIHI.cs    --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ConsumerUpdateIHI     				

dotnet-svcutil wsdl\consumer\20100821\HI_ConsumerCreateUnverifiedIHI*.wsdl    					schema\mca\consumer\messages\20100731\CreateUnverifiedIHIMessages.xsd    					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R302-ConsumerCreateUnverifiedIHI.cs    				  --sync --serializer XmlSerializer --namespace *,nehta.mcaR302.ConsumerCreateUnverifiedIHI      				
dotnet-svcutil wsdl\consumer\20100821\HI_ConsumerResolveProvisionalIHI*.wsdl  					schema\mca\consumer\messages\20100731\ResolveProvisionalIHIMessages.xsd  					schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R302-ConsumerResolveProvisionalIHI.cs  				  --sync --serializer XmlSerializer --namespace *,nehta.mcaR302.ConsumerResolveProvisionalIHI    				

dotnet-svcutil wsdl\consumer\20111201\HI_ConsumerCreateVerifiedIHI*.wsdl   schema\mca\consumer\messages\20111201\CreateVerifiedIHI.xsd   	schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\consumer\core\20100731\*.xsd --outputDir .\net --outputFile R40-CreateVerifiedIHI.cs     --sync --serializer XmlSerializer --namespace *,nehta.mcaR40.CreateVerifiedIHI     					

@echo provider - 10
dotnet-svcutil wsdl\provider\20100930\HI_ProviderManageProviderAdministrativeIndividual*.wsdl    schema\mca\provider\messages\20100930\ManageProviderAdministrativeIndividualMessages.xsd    schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R32-ProviderManageProviderAdministrativeIndividual.cs    --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ProviderManageProviderAdministrativeIndividual      
dotnet-svcutil wsdl\provider\20100930\HI_ProviderManageProviderDirectoryEntry*.wsdl              schema\mca\provider\messages\20100930\ManageProviderDirectoryEntryMessages.xsd              schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R32-ProviderManageProviderDirectoryEntry.cs              --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ProviderManageProviderDirectoryEntry                
dotnet-svcutil wsdl\provider\20100930\HI_ProviderManageProviderOrganisation*.wsdl                schema\mca\provider\messages\20100930\ManageProviderOrganisationMessages.xsd                schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R32-ProviderManageProviderOrganisation.cs                --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ProviderManageProviderOrganisation                  
dotnet-svcutil wsdl\provider\20100930\HI_ProviderReadProviderAdministrativeIndividual*.wsdl      schema\mca\provider\messages\20100930\ReadProviderAdministrativeIndividualMessages.xsd      schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R32-ProviderReadProviderAdministrativeIndividual.cs      --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ProviderReadProviderAdministrativeIndividual        
dotnet-svcutil wsdl\provider\20100930\HI_ProviderReadProviderOrganisation*.wsdl                  schema\mca\provider\messages\20100930\ReadProviderOrganisationMessages.xsd                  schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R32-ProviderReadProviderOrganisation.cs                  --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ProviderReadProviderOrganisation                    
dotnet-svcutil wsdl\provider\20100930\HI_ProviderReadReferenceData*.wsdl                         schema\mca\provider\messages\20100930\ReadReferenceDataMessages.xsd                         schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R32-ProviderReadReferenceData.cs                         --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ProviderReadReferenceData                           
dotnet-svcutil wsdl\provider\20100930\HI_ProviderSearchHIProviderDirectoryForIndividual*.wsdl    schema\mca\provider\messages\20100930\SearchHIProviderDirectoryForIndividualMessages.xsd    schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R32-ProviderSearchHIProviderDirectoryForIndividual.cs    --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ProviderSearchHIProviderDirectoryForIndividual      
dotnet-svcutil wsdl\provider\20100930\HI_ProviderSearchHIProviderDirectoryForOrganisation*.wsdl  schema\mca\provider\messages\20100930\SearchHIProviderDirectoryForOrganisationMessages.xsd  schema\w3c\xmldsig-core-schema.xsd schema\mca\common\20100731\*.xsd schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R32-ProviderSearchHIProviderDirectoryForOrganisation.cs  --sync --serializer XmlSerializer --namespace *,nehta.mcaR32.ProviderSearchHIProviderDirectoryForOrganisation    

dotnet-svcutil wsdl\provider\20130401\HI_ProviderSearchForProviderIndividual*.wsdl     schema\mca\provider\messages\20130401\SearchForProviderIndividualMessages.xsd     schema\w3c\xmldsig-core-schema.xsd   schema\mca\common\20100731\*.xsd   schema\mca\provider\core\20130401\*.xsd  schema\mca\provider\core\20100930\*.xsd --outputDir .\net --outputFile R50-ProviderSearchForProviderIndividual.cs       --sync --serializer XmlSerializer --namespace *,nehta.mcaR50.ProviderSearchForProviderIndividual     					
dotnet-svcutil wsdl\provider\20130401\HI_ProviderSearchForProviderOrganisation*.wsdl   schema\mca\provider\messages\20130401\SearchForProviderOrganisationMessages.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\common\20100731\*.xsd   schema\mca\provider\core\20130401\*.xsd  schema\mca\provider\core\20100930\*.xsd  --outputDir .\net --outputFile R50-ProviderSearchForProviderOrganisation.cs     --sync --serializer XmlSerializer --namespace *,nehta.mcaR50.ProviderSearchForProviderOrganisation     					

dotnet-svcutil wsdl\provider\20130622\HI_ProviderBatchAsyncSearchForProviderIndividual*.wsdl      schema\mca\common\20100731\*.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\provider\core\20130601\ProviderType.xsd         schema\mca\provider\core\20130601\ProviderCoreElements.xsd   schema\mca\provider\core\20130401\*.xsd  schema\mca\provider\core\20100930\*.xsd  schema\mca\provider\messages\20130401\SearchForProviderIndividualMessages.xsd     schema\mca\provider\messages\20130601\RetrieveSearchForProviderIndividualResultsMessages.xsd     schema\mca\provider\messages\20130601\SubmitSearchForProviderIndividualMessages.xsd      --outputDir .\net --outputFile R51-ProviderBatchAsyncSearchForProviderIndividual.cs      --sync --serializer XmlSerializer --namespace *,nehta.mcaR51.ProviderBatchAsyncSearchForProviderIndividual     	
dotnet-svcutil wsdl\provider\20130622\HI_ProviderBatchAsyncSearchForProviderOrganisation*.wsdl    schema\mca\common\20100731\*.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\provider\core\20130601\OrganisationDetails.xsd  schema\mca\provider\core\20130601\ProviderCoreElements.xsd   schema\mca\provider\core\20130401\*.xsd  schema\mca\provider\core\20100930\*.xsd  schema\mca\provider\messages\20130401\SearchForProviderOrganisationMessages.xsd   schema\mca\provider\messages\20130601\RetrieveSearchForProviderOrganisationResultsMessages.xsd   schema\mca\provider\messages\20130601\SubmitSearchForProviderOrganisationMessages.xsd    --outputDir .\net --outputFile R51-ProviderBatchAsyncSearchForProviderOrganisation.cs    --sync --serializer XmlSerializer --namespace *,nehta.mcaR51.ProviderBatchAsyncSearchForProviderOrganisation     	
dotnet-svcutil wsdl\provider\20130622\HI_ProviderManageTdsProviderIndividual*.wsdl              schema\mca\common\20100731\*.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\provider\messages\20100930\ManageTdsProviderIndividualMessages.xsd  schema\mca\provider\core\20100930\*.xsd  schema\mca\provider\core\20130622\*.xsd    --outputDir .\net --outputFile R51-ProviderManageTdsProviderIndividual.cs              --sync --serializer XmlSerializer --namespace *,nehta.mcaR51.ProviderManageTdsProviderIndividual     				
dotnet-svcutil wsdl\provider\20130622\HI_ProviderSearchTdsProviderIndividual*.wsdl              schema\mca\common\20100731\*.xsd   schema\w3c\xmldsig-core-schema.xsd   schema\mca\provider\messages\20100930\SearchTdsProviderIndividualMessages.xsd  schema\mca\provider\core\20100930\*.xsd  schema\mca\provider\core\20130622\*.xsd    --outputDir .\net --outputFile R51-ProviderSearchTdsProviderIndividual.cs              --sync --serializer XmlSerializer --namespace *,nehta.mcaR51.ProviderSearchTdsProviderIndividual     				


DEL *.config
PAUSE

