<?xml version="1.0" encoding="UTF-8"?>
<!--
===========================================================================
@File:          HI_ConsumerResolveProvisionalIHI-3.0.2.wsdl
@Author:        Medicare Australia
@Version:       3.0.2 - Initial version
   		    	2011/06/25 - added backward compatible optional element "hpio" 
	    	 	for Contracted Service Provider usage.  
@CreatedDate:   2010/08/12
@Release:       3.0.2
@Description:   
===========================================================================
-->
<wsdl:definitions 
    xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsp="http://www.w3.org/ns/ws-policy"
    xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
    xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://ns.electronichealth.net.au/hi/svc/ConsumerResolveProvisionalIHI/3.0.2"
    targetNamespace="http://ns.electronichealth.net.au/hi/svc/ConsumerResolveProvisionalIHI/3.0.2"
    name="ConsumerResolveProvisionalIHI">
    <wsp:Policy xml:id="AddressingPolicy">
        <wsam:Addressing/>
    </wsp:Policy>
    <wsp:Policy xml:id="TlsPolicy">
        <sp:TransportBinding>
            <wsp:Policy>
                <sp:TransportToken>
                    <wsp:Policy>
                        <sp:HttpsToken> 
                            <wsp:Policy>
                                <sp:RequireClientCertificate />
                            </wsp:Policy>
                        </sp:HttpsToken>
                    </wsp:Policy>
                </sp:TransportToken>
            </wsp:Policy>
        </sp:TransportBinding>
    </wsp:Policy>
    <wsdl:import 
        namespace="http://ns.electronichealth.net.au/hi/svc/ConsumerResolveProvisionalIHI/3.0.2"
        location="HI_ConsumerResolveProvisionalIHIInterface-3.0.2.wsdl"/>
    <wsdl:binding name="ConsumerResolveProvisionalIHISOAP12Binding" type="tns:ConsumerResolveProvisionalIHIPortType">
        <wsp:PolicyReference URI="#AddressingPolicy"/>
        <wsp:PolicyReference URI="#TlsPolicy"/>
        <wsoap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="resolveProvisionalIHI">
            <wsoap12:operation soapAction="http://ns.electronichealth.net.au/" style="document" />
            <wsdl:input>
                <wsoap12:header message="tns:resolveProvisionalIHIInMsg" part="productHeader" use="literal"/>
                <wsoap12:header message="tns:resolveProvisionalIHIInMsg" part="signatureHeader" use="literal"/>
                <wsoap12:header message="tns:resolveProvisionalIHIInMsg" part="timestampHeader" use="literal"/>
                <wsoap12:header message="tns:resolveProvisionalIHIInMsg" part="userHeader" use="literal"/>
                  <!--	hpio: Backward compatible change, added June 2011 release for CSPs. -->	
                <wsoap12:header message="tns:resolveProvisionalIHIInMsg" part="hpioHeader" use="literal"/>
                <wsoap12:body parts="request" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <wsoap12:header message="tns:resolveProvisionalIHIOutMsg" part="productHeader" use="literal"/>
                <wsoap12:header message="tns:resolveProvisionalIHIOutMsg" part="signatureHeader" use="literal"/>
                <wsoap12:body parts="response" use="literal"/>
            </wsdl:output>
            <wsdl:fault name="standardError">
                <wsoap12:fault name="standardError" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ConsumerResolveProvisionalIHIService">
        <wsdl:port name="ConsumerResolveProvisionalIHISOAP12Port" binding="tns:ConsumerResolveProvisionalIHISOAP12Binding">
            <wsoap12:address location="http://esbservice/soap/services"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>